# integrations/gmail_mcp.py

import json
import os
from models import AuditResult
from logger import get_logger
from config import AUDIT_NOTIFICATION_EMAIL

log = get_logger("gmail_mcp")

# Set this to your email address
NOTIFICATION_EMAIL = os.getenv("AUDIT_NOTIFICATION_EMAIL", "your@email.com")

class GmailMCP:
    """
    Sends audit reports via Gmail using the MCP server.
    
    Uses the Anthropic API with Gmail MCP attached —
    the LLM composes and sends the email in one call.
    """

    async def send_audit_report(self, result: AuditResult):
        """
        Sends a formatted audit report email for high-confidence
        FALSE verdicts. These are the ones worth alerting on.
        """
        verdict = result.verdict.value if hasattr(result.verdict, 'value') \
                  else result.verdict

        log.info(f"Sending audit report email for: '{result.claim_as_stated[:60]}'")

        subject = (
            f"[Epistemic Auditor] {verdict} — "
            f"{result.claim_as_stated[:60]}..."
        )

        body = self._format_email_body(result)

        # Call Anthropic API with Gmail MCP attached
        # The LLM uses the Gmail tool to send the email
        await self._send_via_mcp(subject, body)

    def _format_email_body(self, result: AuditResult) -> str:
        verdict = result.verdict.value if hasattr(result.verdict, 'value') \
                  else result.verdict

        sources_text = "\n".join([
            f"  - {s.get('title', 'Unknown')} ({s.get('url', '')})"
            f" [credibility: {s.get('credibility_score', 0):.2f}]"
            for s in result.sources[:5]
        ]) or "  No sources found"

        atomic_text = "\n".join([
            f"  • {claim}"
            for claim in result.atomic_claims
        ]) or "  No atomic claims extracted"

        return f"""
EPISTEMIC AUDIT REPORT
{'='*50}

CLAIM: {result.claim_as_stated}

VERDICT: {verdict}
CONFIDENCE: {result.confidence:.0%}

ATOMIC CLAIMS ANALYZED:
{atomic_text}

EVIDENCE SUMMARY:
{result.evidence_summary}

ORIGIN HYPOTHESIS:
{result.origin_hypothesis}

PROPAGATION TIMELINE:
{result.timeline_summary}

WHY PEOPLE BELIEVE IT:
{result.why_people_believe_it}

COUNTER-NARRATIVE:
{result.counter_narrative}

SOURCES CONSULTED:
{sources_text}

{'='*50}
Generated by Epistemic Auditor
"""

    async def _send_via_mcp(self, subject: str, body: str):
        """
        Calls the Anthropic API with Gmail MCP server attached.
        The LLM uses the send_email tool to deliver the message.
        """
        import httpx

        payload = {
            "model": "claude-sonnet-4-20250514",
            "max_tokens": 1000,
            "messages": [
                {
                    "role": "user",
                    "content": (
                        f"Please send an email using the Gmail tool with these details:\n"
                        f"To: {NOTIFICATION_EMAIL}\n"
                        f"Subject: {subject}\n"
                        f"Body:\n{body}\n\n"
                        f"Send it now and confirm when done."
                    )
                }
            ],
            "mcp_servers": [
                {
                    "type": "url",
                    "url": "https://gmail.mcp.claude.com/mcp",
                    "name": "gmail-mcp"
                }
            ]
        }

        async with httpx.AsyncClient(timeout=30) as client:
            response = await client.post(
                "https://api.anthropic.com/v1/messages",
                headers={"Content-Type": "application/json"},
                json=payload,
            )
            response.raise_for_status()
            data = response.json()

            # Extract confirmation from response
            text_blocks = [
                block["text"]
                for block in data.get("content", [])
                if block.get("type") == "text"
            ]
            confirmation = " ".join(text_blocks)
            log.info(f"Gmail MCP response: {confirmation[:100]}")
            print(f"[Gmail] Email sent: {confirmation[:80]}")